CREATE DATABASE STOREPHONEDOCTOR;


CREATE TABLE CLIENTES(
    USERNAME_CL         VARCHAR(20)         PRIMARY KEY,
    EMAIL_CL            VARCHAR(50)         NOT NULL UNIQUE,
    CONTRASENA_CL       VARCHAR(50)         NOT NULL,
    NOMBRE_CL           VARCHAR(30)         NOT NULL,
    AP_CL               VARCHAR(30)         NOT NULL,
    AM_CL               VARCHAR(30)         NOT NULL,
    TEL_CL              VARCHAR(15)         NOT NULL,
    MUN_CL              VARCHAR(20)         NOT NULL)
    ENGINE=MYISAM CHARSET=LATIN1 
    COMMENT'REGISTRO DE CLIENTES FRECUENTES';

CREATE TABLE USUARIOS(
    USERNAME_US         VARCHAR(20)         PRIMARY KEY,
    EMAIL_US            VARCHAR(50)         NOT NULL UNIQUE,
    CONTRASENA_US       VARCHAR(50)         NOT NULL,
    NOMBRE_US           VARCHAR(30)         NOT NULL,
    AP_US               VARCHAR(30)         NOT NULL,
    AM_US               VARCHAR(30)         NOT NULL)
    ENGINE=MYISAM CHARSET=LATIN1 
    COMMENT'REGISTRO DE USUARIOS DEL SISTEMA';

CREATE TABLE PRODUCTOS(
    CODIGO_P            VARCHAR(13)         PRIMARY KEY,
    NOMBRE_P            VARCHAR(50)         NOT NULL,
    CATEGORIA_P         VARCHAR(30)         NOT NULL,
    MARCA_P             VARCHAR(30)         NOT NULL,
    CANTIDAD_P          INT                 NOT NULL,
    PRECIO_VENTA_P      FLOAT               NOT NULL,
    PRECIO_COMPRA_P     FLOAT               NOT NULL)
    ENGINE=MYISAM CHARSET=LATIN1 
    COMMENT'REGISTRO DEL INVENTARIO';

CREATE TABLE SERVICIOS(
    FOLIO_S             VARCHAR(10)         PRIMARY KEY,
    USERNAME_US         VARCHAR(20)         NOT NULL,
    USERNAME_CL         VARCHAR(50)         NOT NULL,
    FECHALLEGADA_S      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FECHASALIDA_S       DATE,
    NOMBRECLIENTE_S     VARCHAR(60)         NOT NULL,
    TELEFONOCLIENTE_S   VARCHAR(20)         NOT NULL,
    DESCRIPCION_S       VARCHAR(250)        NOT NULL)
    ENGINE=MYISAM CHARSET=LATIN1 
    COMMENT'BITACORA DE SERVICIOS';

ALTER TABLE SERVICIOS
ADD CONSTRAINT FK_US
FOREIGN KEY(USERNAME_US) REFERENCES USUARIOS(USERNAME_US);

ALTER TABLE SERVICIOS
ADD CONSTRAINT FK_CL
FOREIGN KEY(USERNAME_CL) REFERENCES CLIENTES(USERNAME_CL);

CREATE TABLE VENTAS(
    FOLIO_V             VARCHAR(10)         PRIMARY KEY,
    USERNAME_US         VARCHAR(20)         NOT NULL,
    USERNAME_CL         VARCHAR(50)         NOT NULL,
    FECHA_V             TIMESTAMP           DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CANTIDADPROD_V      INT                 NOT NULL)
    ENGINE=MYISAM CHARSET=LATIN1 
    COMMENT'BITACORA DE VENTAS';

ALTER TABLE VENTAS
ADD CONSTRAINT FK_CL_V
FOREIGN KEY(USERNAME_CL) REFERENCES CLIENTES(USERNAME_CL);
ALTER TABLE VENTAS
ADD CONSTRAINT FK_US_V
FOREIGN KEY(USERNAME_US) REFERENCES USUARIOS(USERNAME_US);

CREATE TABLE VENTAS_PRODUCTO(
    ID_VP               VARCHAR(5)          PRIMARY KEY,
    FOLIO_V             VARCHAR(10)         NOT NULL,
    CODIGO_P            VARCHAR(13)         NOT NULL)
    ENGINE=MYISAM CHARSET=LATIN1 
    COMMENT'PRODUCTOS VENDIDOS';

ALTER TABLE VENTAS_PRODUCTO
ADD CONSTRAINT FK_V
FOREIGN KEY(FOLIO_V) REFERENCES VENTAS(FOLIO_V);

ALTER TABLE VENTAS_PRODUCTO
ADD CONSTRAINT FK_P
FOREIGN KEY(CODIGO_P) REFERENCES PRODUCTOS(CODIGO_P);

CREATE VIEW IMPORTE_DE_V AS
SELECT PRECIO_VENTA_P * CANTIDADPROD_V AS IMPORTE_V FROM PRODUCTOS, VENTAS;

CREATE VIEW INVENTARIO_NO_ADMN AS
SELECT NOMBRE_P, CANTIDAD_P, PRECIO_VENTA_P 
FROM PRODUCTOS;

CREATE VIEW SERVICIOS_NO_ADM AS
SELECT FOLIO_S,FECHALLEGADA_S,NOMBRECLIENTE_S,TELEFONOCLIENTE_S,DESCRIPCION_S FROM SERVICIOS;

CREATE VIEW SERVICIOS_NO_ADM_DOS AS
SELECT FOLIO_S,FECHALLEGADA_S,NOMBRE_CL FROM SERVICIOS
INNER JOIN CLIENTES WHERE SERVICIOS.USERNAME_CL=CLIENTES.USERNAME_CL;




