/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import java.awt.Image; /*Se importo la libreria Image*/
import java.awt.Toolkit; /*Se importo la libreria Toolkit*/
/**
 *
 * @author Norberto
 */
public class JFRegistro extends javax.swing.JFrame {

    /**
     * Creates new form JFLogin
     */
    public JFRegistro() {
        initComponents();
        this.setLocationRelativeTo(null); /*Esta funcion permite centrar el JFrame*/
        this.setResizable(false); /*Evita que la ventana se Maximize*/
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/Icon.png"));
        return retValue;/*Se genero una clase donde se manda llamar un icono para JFrame*/
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldIngUsuario = new javax.swing.JTextField();
        jPasswordFieldIngContraseña = new javax.swing.JPasswordField();
        jLabelIconUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegistrarse = new javax.swing.JButton();
        jLabelIngNombre = new javax.swing.JLabel();
        jLabelIngCorreo = new javax.swing.JLabel();
        jLabelIngApellidoM = new javax.swing.JLabel();
        jLabelIngApellidoP = new javax.swing.JLabel();
        jPasswordFieldVerifContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldIngIngApellP = new javax.swing.JTextField();
        jTextFieldIngNombreUsuario1 = new javax.swing.JTextField();
        jTextFieldIngIngApellP1 = new javax.swing.JTextField();
        jTextFieldIngIngApellP2 = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio De Sesión (StorePhone Doctor)");
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldIngUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIngUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldIngUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldIngUsuario.setAutoscrolls(false);
        jTextFieldIngUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIngUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, -1));

        jPasswordFieldIngContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldIngContraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPasswordFieldIngContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordFieldIngContraseña.setAutoscrolls(false);
        getContentPane().add(jPasswordFieldIngContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 190, -1));

        jLabelIconUser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelIconUser.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIconUser.setText("Nombre de Usuario:");
        jLabelIconUser.setAlignmentX(0.5F);
        getContentPane().add(jLabelIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 20));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Contraseña:");
        jLabel1.setAlignmentX(0.5F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, 20));

        jButtonRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonRegistrarse.setText("Registrarse");
        getContentPane().add(jButtonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 100, -1));

        jLabelIngNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelIngNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIngNombre.setText("Nombre:");
        jLabelIngNombre.setAlignmentX(0.5F);
        getContentPane().add(jLabelIngNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 50, 20));

        jLabelIngCorreo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelIngCorreo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIngCorreo.setText("Correo electronico:");
        jLabelIngCorreo.setAlignmentX(0.5F);
        getContentPane().add(jLabelIngCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 120, 20));

        jLabelIngApellidoM.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelIngApellidoM.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIngApellidoM.setText("Apellido Paterno:");
        jLabelIngApellidoM.setAlignmentX(0.5F);
        getContentPane().add(jLabelIngApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 100, -1));

        jLabelIngApellidoP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelIngApellidoP.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIngApellidoP.setText("Apellido Materno:");
        jLabelIngApellidoP.setAlignmentX(0.5F);
        getContentPane().add(jLabelIngApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 100, 20));

        jPasswordFieldVerifContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldVerifContraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPasswordFieldVerifContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordFieldVerifContraseña.setAutoscrolls(false);
        getContentPane().add(jPasswordFieldVerifContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 190, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Verificar Contraseña:");
        jLabel2.setAlignmentX(0.5F);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, 20));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 80, -1));

        jTextFieldIngIngApellP.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIngIngApellP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldIngIngApellP.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldIngIngApellP.setAutoscrolls(false);
        jTextFieldIngIngApellP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngIngApellPActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIngIngApellP, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 190, -1));

        jTextFieldIngNombreUsuario1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIngNombreUsuario1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldIngNombreUsuario1.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldIngNombreUsuario1.setAutoscrolls(false);
        jTextFieldIngNombreUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngNombreUsuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIngNombreUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 190, -1));

        jTextFieldIngIngApellP1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIngIngApellP1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldIngIngApellP1.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldIngIngApellP1.setAutoscrolls(false);
        jTextFieldIngIngApellP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngIngApellP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIngIngApellP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 190, -1));

        jTextFieldIngIngApellP2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIngIngApellP2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldIngIngApellP2.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldIngIngApellP2.setAutoscrolls(false);
        jTextFieldIngIngApellP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngIngApellP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIngIngApellP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 190, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIngUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngUsuarioActionPerformed

    private void jTextFieldIngIngApellPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngIngApellPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngIngApellPActionPerformed

    private void jTextFieldIngNombreUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngNombreUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngNombreUsuario1ActionPerformed

    private void jTextFieldIngIngApellP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngIngApellP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngIngApellP1ActionPerformed

    private void jTextFieldIngIngApellP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngIngApellP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngIngApellP2ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        JFLogin login = new JFLogin();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIconUser;
    private javax.swing.JLabel jLabelIngApellidoM;
    private javax.swing.JLabel jLabelIngApellidoP;
    private javax.swing.JLabel jLabelIngCorreo;
    private javax.swing.JLabel jLabelIngNombre;
    private javax.swing.JPasswordField jPasswordFieldIngContraseña;
    private javax.swing.JPasswordField jPasswordFieldVerifContraseña;
    private javax.swing.JTextField jTextFieldIngIngApellP;
    private javax.swing.JTextField jTextFieldIngIngApellP1;
    private javax.swing.JTextField jTextFieldIngIngApellP2;
    private javax.swing.JTextField jTextFieldIngNombreUsuario1;
    private javax.swing.JTextField jTextFieldIngUsuario;
    // End of variables declaration//GEN-END:variables
}
