/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modelo.SqlUsuarios;
import modelo.hash;
import modelo.usuarios;

/**
 *
 * @author Norberto
 */
public class JFLogin extends javax.swing.JFrame {

    public static JFLogin log;
    public static JFRegistro reg;
    public static JFMenuPrincipal menu;

    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();

        ImageIcon imagenLogin = new ImageIcon(getClass().getResource("/Images/FondoPrograma.png"));
        Image fondoLogin = imagenLogin.getImage().getScaledInstance(jLabelFondoLogin.getWidth(), jLabelFondoLogin.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscaladoLogin = new ImageIcon(fondoLogin);
        jLabelFondoLogin.setIcon(iconoEscaladoLogin);

        ImageIcon imagenLogo = new ImageIcon(getClass().getResource("/Images/LogoPrincipal.png"));
        Image fondoLogo = imagenLogo.getImage().getScaledInstance(jLabelLogoLogin.getWidth(), jLabelLogoLogin.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscaladoLogo = new ImageIcon(fondoLogo);
        jLabelLogoLogin.setIcon(iconoEscaladoLogo);

        this.setLocationRelativeTo(null);
        /*Esta funcion permite centrar el JFrame*/
        this.setResizable(false);
        /*Evita que la ventana se Maximize*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldUsuario = new javax.swing.JPasswordField();
        jButtonIniciarSesion = new javax.swing.JButton();
        jLabelIconUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegistrarse = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelRecuperarContraseña = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelLogoLogin = new javax.swing.JLabel();
        jLabelFondoLogin = new javax.swing.JLabel();
        jTextFieldTomarUsuario = new javax.swing.JTextField();
        jTextFieldTomarTipoUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio De Sesión (StorePhone Doctor)");
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 240, 40));
        getContentPane().add(jPasswordFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 240, 40));

        jButtonIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonIniciarSesion.setText("Iniciar Sesión");
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 240, 40));

        jLabelIconUser.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabelIconUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconUsuario.png"))); // NOI18N
        jLabelIconUser.setText("Usuario:");
        getContentPane().add(jLabelIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, 40));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconPassword.png"))); // NOI18N
        jLabel1.setText("Contraseña:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, 40));

        jButtonRegistrarse.setBackground(java.awt.Color.white);
        jButtonRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonRegistrarse.setText("Registrarse");
        jButtonRegistrarse.setToolTipText("");
        jButtonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 220, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 220, 10));

        jLabelRecuperarContraseña.setText("¿Olvidaste tu Usuario o Contraseña?");
        getContentPane().add(jLabelRecuperarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 250, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconClose.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 100, 30));

        jLabelLogoLogin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabelLogoLoginPropertyChange(evt);
            }
        });
        getContentPane().add(jLabelLogoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 330));
        getContentPane().add(jLabelFondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 370));

        jTextFieldTomarUsuario.setEnabled(false);
        getContentPane().add(jTextFieldTomarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        jTextFieldTomarTipoUsuario.setEnabled(false);
        getContentPane().add(jTextFieldTomarTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);/*Boton que permite cerrar JFrame*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
        SqlUsuarios modSql = new SqlUsuarios();
        usuarios mod = new usuarios();

        String pass = new String(jPasswordFieldUsuario.getPassword());

        if (!jTextFieldUsuario.getText().equals("") && !pass.equals("")) {
            String nuevoPass = hash.sha1(pass);

            mod.setUsername(jTextFieldUsuario.getText());
            mod.setContrasena_user(nuevoPass);

            if (modSql.login(mod)) {
                if (menu == null) {
                    jTextFieldTomarTipoUsuario.setText(mod.getTipo_user());
                    jTextFieldTomarUsuario.setText(mod.getUsername());
                    JFMenuPrincipal frm = new JFMenuPrincipal();
                    frm.setVisible(true);
                    frm.USUARIOMENU.setText(jTextFieldTomarUsuario.getText());
                    frm.TIPOUSUARIOMENU.setText(jTextFieldTomarTipoUsuario.getText());

                    this.dispose();;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Datos Incorrectos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar sus datos");
        }
    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    private void jButtonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseActionPerformed
        if (reg == null) {
            reg = new JFRegistro();
            reg.setVisible(true);

            this.dispose();

        }

    }//GEN-LAST:event_jButtonRegistrarseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JFLogin.log = null;
    }//GEN-LAST:event_formWindowClosing

    private void jLabelLogoLoginPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabelLogoLoginPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelLogoLoginPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Thread(new JFSplash()).start();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondoLogin;
    private javax.swing.JLabel jLabelIconUser;
    private javax.swing.JLabel jLabelLogoLogin;
    private javax.swing.JLabel jLabelRecuperarContraseña;
    private javax.swing.JPasswordField jPasswordFieldUsuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField jTextFieldTomarTipoUsuario;
    public javax.swing.JTextField jTextFieldTomarUsuario;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
