/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.SqlUsuarios;
import modelo.hash;
import modelo.usuarios;
import Ventanas.JFMenuPrincipal;

/**
 *
 * @author Norberto
 */
public class JFRegistro extends javax.swing.JFrame {

    public static JFMenuPrincipal menuP;

    /**
     * Creates new form JFLogin
     */
    public JFRegistro() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("../Images/blanco-logo.png")).getImage());
        
        ImageIcon imagenLogin = new ImageIcon(getClass().getResource("/Images/FondoPrograma.png"));
        Image fondoLogin = imagenLogin.getImage().getScaledInstance(jLabelFondoLogin.getWidth(), jLabelFondoLogin.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscaladoLogin = new ImageIcon(fondoLogin);
        jLabelFondoLogin.setIcon(iconoEscaladoLogin);

        ImageIcon imagenLogo = new ImageIcon(getClass().getResource("/Images/LogoPrincipal.png"));
        Image fondoLogo = imagenLogo.getImage().getScaledInstance(jLabelLogoLogin.getWidth(), jLabelLogoLogin.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscaladoLogo = new ImageIcon(fondoLogo);
        jLabelLogoLogin.setIcon(iconoEscaladoLogo);
        this.setLocationRelativeTo(null);
        /*Esta funcion permite centrar el JFrame*/
        this.setResizable(false);
        /*Evita que la ventana se Maximize*/
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldIngUsuario = new javax.swing.JTextField();
        jPasswordFieldIngContraseña = new javax.swing.JPasswordField();
        jLabelIconUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegistrarse = new javax.swing.JButton();
        jLabelIngNombre = new javax.swing.JLabel();
        jLabelIngCorreo = new javax.swing.JLabel();
        jLabelIngApellidoM = new javax.swing.JLabel();
        jLabelIngApellidoP = new javax.swing.JLabel();
        jPasswordFieldVerifContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldCorreoUsuario = new javax.swing.JTextField();
        jTextFieldIngNombreUsuario = new javax.swing.JTextField();
        jTextFieldIngIngApellPUsuario = new javax.swing.JTextField();
        jTextFieldIngIngApellMUsuario = new javax.swing.JTextField();
        jLabelLogoLogin = new javax.swing.JLabel();
        jLabelTipoEmp = new javax.swing.JLabel();
        jComboBoxTipoUser = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        TIPOUSUARIOMENU = new javax.swing.JLabel();
        USUARIOMENU = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelFondoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio De Sesión (StorePhone Doctor)");
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldIngUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldIngUsuario.setAutoscrolls(false);
        jTextFieldIngUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIngUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, -1));

        jPasswordFieldIngContraseña.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPasswordFieldIngContraseña.setAutoscrolls(false);
        getContentPane().add(jPasswordFieldIngContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 190, -1));

        jLabelIconUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelIconUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIconUser.setText("Nombre de Usuario:");
        jLabelIconUser.setAlignmentX(0.5F);
        getContentPane().add(jLabelIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 20));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña:");
        jLabel1.setAlignmentX(0.5F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, 20));

        jButtonRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonRegistrarse.setText("Registrarse");
        jButtonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 100, -1));

        jLabelIngNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelIngNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIngNombre.setText("Nombre:");
        jLabelIngNombre.setAlignmentX(0.5F);
        getContentPane().add(jLabelIngNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 50, 20));

        jLabelIngCorreo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelIngCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIngCorreo.setText("Correo electronico:");
        jLabelIngCorreo.setAlignmentX(0.5F);
        getContentPane().add(jLabelIngCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 120, 20));

        jLabelIngApellidoM.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelIngApellidoM.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIngApellidoM.setText("Apellido Paterno:");
        jLabelIngApellidoM.setAlignmentX(0.5F);
        getContentPane().add(jLabelIngApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 100, 20));

        jLabelIngApellidoP.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelIngApellidoP.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIngApellidoP.setText("Apellido Materno:");
        jLabelIngApellidoP.setAlignmentX(0.5F);
        getContentPane().add(jLabelIngApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 100, 20));

        jPasswordFieldVerifContraseña.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPasswordFieldVerifContraseña.setAutoscrolls(false);
        getContentPane().add(jPasswordFieldVerifContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 190, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Verificar Contraseña:");
        jLabel2.setAlignmentX(0.5F);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, 20));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 80, -1));

        jTextFieldCorreoUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldCorreoUsuario.setAutoscrolls(false);
        jTextFieldCorreoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCorreoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 190, -1));

        jTextFieldIngNombreUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldIngNombreUsuario.setAutoscrolls(false);
        jTextFieldIngNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngNombreUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIngNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 190, -1));

        jTextFieldIngIngApellPUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldIngIngApellPUsuario.setAutoscrolls(false);
        jTextFieldIngIngApellPUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngIngApellPUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIngIngApellPUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 190, -1));

        jTextFieldIngIngApellMUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldIngIngApellMUsuario.setAutoscrolls(false);
        jTextFieldIngIngApellMUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngIngApellMUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIngIngApellMUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 190, -1));
        getContentPane().add(jLabelLogoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 280));

        jLabelTipoEmp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelTipoEmp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoEmp.setText("Tipo:");
        jLabelTipoEmp.setAlignmentX(0.5F);
        getContentPane().add(jLabelTipoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 30, 20));

        jComboBoxTipoUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBoxTipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Administrador", "Usuario" }));
        getContentPane().add(jComboBoxTipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 190, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "sesión", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        TIPOUSUARIOMENU.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        TIPOUSUARIOMENU.setForeground(new java.awt.Color(255, 255, 255));

        USUARIOMENU.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        USUARIOMENU.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Categoria:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(USUARIOMENU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TIPOUSUARIOMENU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USUARIOMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TIPOUSUARIOMENU, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 180, -1));
        getContentPane().add(jLabelFondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIngUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngUsuarioActionPerformed

    private void jTextFieldCorreoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoUsuarioActionPerformed

    private void jTextFieldIngNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngNombreUsuarioActionPerformed

    private void jTextFieldIngIngApellPUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngIngApellPUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngIngApellPUsuarioActionPerformed

    private void jTextFieldIngIngApellMUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngIngApellMUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngIngApellMUsuarioActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int cancelar = JOptionPane.showConfirmDialog(null, "¿Desea cancelar el registro?", "Confirmar salida", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (cancelar == 0) {
            if (menuP == null) {
                JFMenuPrincipal men = new JFMenuPrincipal();
                men.setVisible(true);
                men.USUARIOMENU.setText(USUARIOMENU.getText());
                men.TIPOUSUARIOMENU.setText(TIPOUSUARIOMENU.getText());
                this.setVisible(false);
                this.dispose();
            }
        } else {
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseActionPerformed
        String userNew = jTextFieldIngNombreUsuario.getText();
        int cancelar = JOptionPane.showConfirmDialog(null, "¿Quiere agregar este nuevo usuario?", "Nuevo Usuario", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (cancelar == 0) {

            SqlUsuarios modSql = new SqlUsuarios(); //Se creaun nuevo objeto de la clase SqlUsuarios llamadp modSql
            usuarios mod = new usuarios(); //Se crea un nuevo objeto de la clase usuarios llamado mod

            String pass = new String(jPasswordFieldIngContraseña.getPassword()); //Se crea una nueva variable String para extraer la contraseña ingresada en el textField
            String passcon = new String(jPasswordFieldVerifContraseña.getPassword()); //Nueva variable para extraer el texto del TextField
            String nuevoTipoUser = jComboBoxTipoUser.getSelectedItem().toString();

            try {
                if (pass.equals("") || jTextFieldIngUsuario.getText().equals("") || jTextFieldIngIngApellPUsuario.getText().equals("") || jTextFieldIngIngApellMUsuario.getText().equals("") || jTextFieldIngNombreUsuario.getText().equals("") || jTextFieldCorreoUsuario.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Debe llenar todos los campos\n¡No se permiten campos vacios!");
                } else {
                    if (pass.equals(passcon)) {
                        if (modSql.existeUsuario(jTextFieldIngUsuario.getText()) == 0) {
                            if (modSql.esEmail(jTextFieldCorreoUsuario.getText())) {
                                String nuevoPass = hash.sha1(pass);

                                if (!nuevoTipoUser.equals("Selecciona")) {
                                    mod.setUsername(jTextFieldIngUsuario.getText());
                                    mod.setEmail_user(jTextFieldCorreoUsuario.getText());
                                    mod.setContrasena_user(nuevoPass);
                                    mod.setNombre_user(jTextFieldIngNombreUsuario.getText());
                                    mod.setAp_user(jTextFieldIngIngApellPUsuario.getText());
                                    mod.setAm_user(jTextFieldIngIngApellMUsuario.getText());
                                    mod.setTipo_user(nuevoTipoUser);

                                    limpiar();

                                    if (modSql.registrarUsers(mod)) {
                                        JOptionPane.showMessageDialog(null, "El registro fue guardado");
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Error al guardar");
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Selecciona el tipo de usuario");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "El correo no es valido");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "El usuario ya existe");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
                    }
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al guardar\n" + ex);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "No se ha guardado ningun Usuario");
        }

    }//GEN-LAST:event_jButtonRegistrarseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JFLogin.reg = null;
    }//GEN-LAST:event_formWindowClosing

    private void limpiar() {
        jTextFieldIngUsuario.setText("");
        jPasswordFieldIngContraseña.setText("");
        jPasswordFieldVerifContraseña.setText("");
        jTextFieldIngNombreUsuario.setText("");
        jTextFieldIngIngApellPUsuario.setText("");
        jTextFieldIngIngApellMUsuario.setText("");
        jTextFieldCorreoUsuario.setText("");
        jComboBoxTipoUser.setSelectedItem("Selecciona");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel TIPOUSUARIOMENU;
    public javax.swing.JLabel USUARIOMENU;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JComboBox<String> jComboBoxTipoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFondoLogin;
    private javax.swing.JLabel jLabelIconUser;
    private javax.swing.JLabel jLabelIngApellidoM;
    private javax.swing.JLabel jLabelIngApellidoP;
    private javax.swing.JLabel jLabelIngCorreo;
    private javax.swing.JLabel jLabelIngNombre;
    private javax.swing.JLabel jLabelLogoLogin;
    private javax.swing.JLabel jLabelTipoEmp;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldIngContraseña;
    private javax.swing.JPasswordField jPasswordFieldVerifContraseña;
    private javax.swing.JTextField jTextFieldCorreoUsuario;
    private javax.swing.JTextField jTextFieldIngIngApellMUsuario;
    private javax.swing.JTextField jTextFieldIngIngApellPUsuario;
    private javax.swing.JTextField jTextFieldIngNombreUsuario;
    private javax.swing.JTextField jTextFieldIngUsuario;
    // End of variables declaration//GEN-END:variables
}
